#!/bin/sh

# Load config
. $( pwd -P )"/deploy-config.sh"

# Get the pushed branch name
oldrev=$(git rev-parse $1)
newrev=$(git rev-parse $2)
refname="$3"
while read oldrev newrev refname; do
    current_branch=$refname
    short_current_branch="$(echo $current_branch | sed 's/refs\/heads\///g')"
done

# Check if push to the configured branch
if [ "$short_current_branch" != $working_branch ]; then
  echo
  echo "Prevented push to $short_current_branch branch."
  echo "Push is accepted only to $working_branch branch."
  echo
  exit 1
fi

# Define live repository
live_repo_path=$( pwd -P )"/"$live_repo_relative_path

# Get live repository status
git_live_status=$(cd $live_repo_path ; env -i git status --porcelain)

if [ "$GIT_PUSH_OPTION_0" = "from_live" ]; then
    echo
	echo "Push from live: accepted unconditionally."
else
    # Normal push, some verifications needed

    if [ -z "$git_live_status" ]; then
        echo
        echo "Live repository clean, push accepted."
    else
        echo
        echo "Live repository not clean, updating live."
        echo "Pushing from live to bare..."

        # Commiting live changes in live repository
        # --author option on commit doesn't work, using -c
        cd $live_repo_path
        env -i git add -A
        env -i git -c user.email="$user_email" -c user.name="$user_name" commit -m "[autocommit]" --quiet
        env -i git push bare master --push-option="from_live" --quiet

        echo "Done"
        echo
        echo "Remote contains work that you do not have locally."
        echo "Pull before pushing again."
        echo
        exit 1
    fi
fi
